
version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: Cx

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch
    steps:
      - checkout
 
      - run:
          name: Install CxCLI Plugin
          command: |
            wget -O ~/cxflow.jar https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.15/cx-flow-1.6.15.jar
            echo $CIRCLE_PROJECT_REPONAME
 
      - run:
          name: Execute CxSAST Scan
          command: |
            mv ~/project/.checkmarx/application.yml ~/project
            cd ~/project
            java -jar ~/cxflow.jar --spring.config.location=application.yml \
              --scan --f="/home/circleci/project" \
              --cx-team="$CX_TEAM" \
              --cx-project="$CIRCLE_PROJECT_REPONAME" \
              --app="$CIRCLE_PROJECT_REPONAME" \
              --cx-flow.bugTracker="Json" \
              --checkmarx.base-url=$CX_SERVER \
              --checkmarx.username=$CX_USER \
              --checkmarx.password=$CX_PASSWORD \
              --sca.tenant=$CX_SCA_TENANT \
              --sca.username=$CX_SCA_USER \
              --sca.password=$CX_SCA_PWD \
              --json.file-name-format=${CIRCLE_PROJECT_REPONAME}.json
            ls  
              
      - store_artifacts:
          path: /home/circleci/${CIRCLE_PROJECT_REPONAME}.json
          
       
      - run:
          name: List files
          command: |
            ls
            
